// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw62gxfZemaY94UxagFzS33DqqbMXIUEc',
    appId: '1:386424211650:web:2827d0b0ef70a8655f535b',
    messagingSenderId: '386424211650',
    projectId: 'e-commerce-53a52',
    authDomain: 'e-commerce-53a52.firebaseapp.com',
    storageBucket: 'e-commerce-53a52.appspot.com',
    measurementId: 'G-SQT6T9GKM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTmpKTzL8ctLl-MilmC-MQzBYSiGMEcw',
    appId: '1:386424211650:android:366cf7d9ee0f84cb5f535b',
    messagingSenderId: '386424211650',
    projectId: 'e-commerce-53a52',
    storageBucket: 'e-commerce-53a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5XvznmLXtEaPf2BgQlpNt0xgaCNxZEOQ',
    appId: '1:386424211650:ios:ecb436b5285a77265f535b',
    messagingSenderId: '386424211650',
    projectId: 'e-commerce-53a52',
    storageBucket: 'e-commerce-53a52.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5XvznmLXtEaPf2BgQlpNt0xgaCNxZEOQ',
    appId: '1:386424211650:ios:ecb436b5285a77265f535b',
    messagingSenderId: '386424211650',
    projectId: 'e-commerce-53a52',
    storageBucket: 'e-commerce-53a52.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw62gxfZemaY94UxagFzS33DqqbMXIUEc',
    appId: '1:386424211650:web:1849eaa60a5111715f535b',
    messagingSenderId: '386424211650',
    projectId: 'e-commerce-53a52',
    authDomain: 'e-commerce-53a52.firebaseapp.com',
    storageBucket: 'e-commerce-53a52.appspot.com',
    measurementId: 'G-F6Z9L1KDSM',
  );
}
